workflows:
  ios-simulator:
    name: iOS Simulator Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean and get Flutter dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Pre-cache Flutter iOS artifacts
        script: flutter precache --ios

      - name: Install CocoaPods
        script: |
          cd ios
          rm -rf Pods Podfile.lock .symlinks
          pod install --repo-update
          cd ..

      - name: Build iOS simulator
        script: flutter build ios --debug --simulator -t lib/main.dart

    artifacts:
      - build/ios/iphonesimulator/Runner.app

    publishing:
      email:
        recipients:
          - teabanimehdi@gmail.com
