workflows:
  ios-flavor:   # <-- this is the workflow ID
    name: iOS Flavor Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        PROJECT_PATH: .
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Pre-build iOS
        script: |
          flutter clean
          cd ios
          rm -rf Pods Podfile.lock
          pod install
          cd ..
      - name: Build iOS
        script: flutter build ios --debug --no-codesign -t lib/main.dart
    artifacts:
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - teabanimehdi@gmail.com
