workflows:
  ios-flavor:
    name: iOS Flavor Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        PROJECT_PATH: .
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Pre-build iOS
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install
          cd ..
      - name: Build iOS
        script: flutter build ios --debug --no-codesign --flavor ios-production -t lib/main_prod.dart
    artifacts:
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - teabanimehdi@gmail.com

  android-flavor:
    name: Android Flavor Build
    environment:
      flutter: stable
      vars:
        PROJECT_PATH: .
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Build Android
        script: flutter build apk --debug --flavor android-production -t lib/main_prod.dart
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - teabanimehdi@gmail.com

  web-flavor:
    name: Web Flavor Build
    environment:
      flutter: stable
      vars:
        PROJECT_PATH: .
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Build Web
        script: flutter build web -t lib/main_prod.dart
    artifacts:
      - build/web/**
    publishing:
      email:
        recipients:
          - teabanimehdi@gmail.com
