workflows:
  ios-flavor:
    name: iOS Simulator Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      # 1. Clean and get dependencies
      - name: Install Flutter dependencies
        script: |
          flutter clean
          flutter pub get

      # 2. Pre-cache Flutter iOS artifacts
      - name: Pre-build iOS
        script: flutter precache --ios

      # 3. Install CocoaPods dependencies
      - name: Install pods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      # 4. Build for iOS simulator (no signing needed)
      - name: Build iOS app for simulator
        script: flutter build ios --debug --simulator -t lib/main.dart

    artifacts:
      - build/ios/iphonesimulator/*.app

    publishing:
      email:
        recipients:
          - teabanimehdi@gmail.com
