workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      # 1. Get dependencies
      - name: Install Flutter dependencies
        script: |
          flutter clean
          flutter pub get

      # 2. Generate iOS ephemeral files (creates Flutter/Flutter.h)
      - name: Build iOS in debug mode to create ephemeral
        script: |
          flutter precache --ios
          flutter build ios --debug --no-codesign

      # 3. Install CocoaPods
      - name: Install pods
        script: |
          cd ios
          pod install --repo-update
          cd ..

    artifacts:
      - build/ios/ipa/*.ipa
