workflows:
  ios-flavor:
    name: iOS Flavor Build
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      # 1. Remove old CocoaPods
      - name: Remove old CocoaPods
        script: |
          echo "Removing old CocoaPods..."
          sudo gem uninstall cocoapods -aIx || true
          sudo rm -f /usr/local/bin/pod || true

      # 2. Install CocoaPods using Homebrew
      - name: Install CocoaPods via Homebrew
        script: |
          echo "Installing CocoaPods via Homebrew..."
          brew install cocoapods
          pod --version

      # 3. Update CocoaPods repository
      - name: Update CocoaPods repo
        script: |
          echo "Updating CocoaPods repo..."
          pod setup

      # 4. Install iOS dependencies
      - name: Install Pods
        script: |
          cd ios
          pod install --repo-update

      # 5. Flutter build for iOS
      - name: Build iOS app
        script: |
          flutter clean
          flutter pub get
          flutter build ios --release --no-codesign
