workflows:
  ios-flavor:
    name: iOS Flavor Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        PROJECT_PATH: .
    scripts:
      - name: Flutter clean
        script: flutter clean

      - name: Flutter pub get
        script: flutter pub get

      - name: Clean & Install iOS Pods
        script: |
          echo "Cleaning previous Pods..."
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install
          cd ..

      - name: Build iOS
        script: flutter build ios --debug --no-codesign -t lib/main.dart

    artifacts:
      - build/ios/iphoneos/*.app

    publishing:
      email:
        recipients:
          - teabanimehdi@gmail.com
