// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBznnDXz9m08Znc5QlGBEPP7zHWBddxpPk',
    appId: '1:256430814249:web:7dc6cb22dc41aaff861838',
    messagingSenderId: '256430814249',
    projectId: 'my-archive-app-01',
    authDomain: 'my-archive-app-01.firebaseapp.com',
    storageBucket: 'my-archive-app-01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_Pk0U1rk2Nf5t8cv9ATrSm2XNzTvBT7U',
    appId: '1:256430814249:android:20bfa05b73d5adab861838',
    messagingSenderId: '256430814249',
    projectId: 'my-archive-app-01',
    storageBucket: 'my-archive-app-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIa9uGXCGGmwT8Bbh1UGXXArRd9m1UDVY',
    appId: '1:256430814249:ios:8af0f2bb3111567c861838',
    messagingSenderId: '256430814249',
    projectId: 'my-archive-app-01',
    storageBucket: 'my-archive-app-01.firebasestorage.app',
    iosBundleId: 'com.example.archiveAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIa9uGXCGGmwT8Bbh1UGXXArRd9m1UDVY',
    appId: '1:256430814249:ios:8af0f2bb3111567c861838',
    messagingSenderId: '256430814249',
    projectId: 'my-archive-app-01',
    storageBucket: 'my-archive-app-01.firebasestorage.app',
    iosBundleId: 'com.example.archiveAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBznnDXz9m08Znc5QlGBEPP7zHWBddxpPk',
    appId: '1:256430814249:web:0e8e1f2d14747fe7861838',
    messagingSenderId: '256430814249',
    projectId: 'my-archive-app-01',
    authDomain: 'my-archive-app-01.firebaseapp.com',
    storageBucket: 'my-archive-app-01.firebasestorage.app',
  );
}
